using System;
using System.Collections.Generic;
using System.EnterpriseServices;
using System.Linq;
using System.Runtime.Serialization;
using System.Security.Cryptography.X509Certificates;
using System.ServiceModel;
using System.ServiceModel.Web;
using System.Text;
using AvventoWebService.DataContracts;
using Stt.Derivatives.Api;

namespace AvventoWebService
{
    // NOTE: You can use the "Rename" command on the "Refactor" menu to change the interface name "IService1" in both code and config file together.
    /// <summary>
    /// 
    /// </summary>
    /// <autogeneratedoc />
    [ServiceContract( SessionMode = SessionMode.Required)]
    public interface IAvventoService
    {


        /// <summary>Sends the login message.</summary>
        /// <param name="userName">Name of the user.</param>
        /// <param name="password">The password.</param>
        /// <returns></returns>

        [OperationContract(Name = "LoginAction", IsInitiating = true, IsTerminating =false)]
       // [FaultContract(typeof(OperationException))]
        [WebInvoke(Method = "*", ResponseFormat = WebMessageFormat.Xml,BodyStyle = WebMessageBodyStyle.Wrapped)]

        string Login(string userName, string password);


       

        [OperationContract(Name = "DataDownloadAction", IsInitiating = false, IsTerminating = false)]
        //[FaultContract(typeof(OperationException))]
        [WebInvoke(Method = "*", ResponseFormat = WebMessageFormat.Xml, BodyStyle = WebMessageBodyStyle.Wrapped)]
        byte[] DatasetDownload(string actionQuery);


        /// <summary>Submits the action.</summary>
        /// <param name="actionQuery">The action query.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        [OperationContract(Name = "SubmitAction", IsInitiating = false, IsTerminating = false)]
       // [FaultContract(typeof(OperationException))]
        [WebInvoke(Method = "*", ResponseFormat = WebMessageFormat.Xml, BodyStyle = WebMessageBodyStyle.Wrapped)]
        string SubmitAction(string actionQuery);

      
        /// <summary>Logouts the specified user name.</summary>
        /// <returns></returns>
        [OperationContract(Name = "LogoutAction", IsInitiating = false, IsTerminating = true)]
       // [FaultContract(typeof(OperationException))]
        [WebInvoke(Method = "*", ResponseFormat = WebMessageFormat.Xml, BodyStyle = WebMessageBodyStyle.Wrapped)]


        void Logout();

        [OperationContract(Name = "Version", IsInitiating = false, IsTerminating = false)]
        // [FaultContract(typeof(OperationException))]
        [WebInvoke(Method = "*", ResponseFormat = WebMessageFormat.Xml, BodyStyle = WebMessageBodyStyle.Wrapped)]
        string Version();

    }

   



}
